import os

from tonos_ts4 import ts4

BUILD_ARTIFACTS_PATH = os.path.dirname(os.path.realpath(__file__)) + '/../../build/'
VERBOSE = os.getenv('VERBOSE', 'False').lower() == 'true'

NAME = 'TestToken'
SYMBOL = 'TT'
DECIMALS = 9

DEPLOY_WALLET_VALUE = int(0.1 * ts4.GRAM)
TARGET_WALLET_BALANCE = int(0.1 * ts4.GRAM)
TARGET_ROOT_BALANCE = ts4.GRAM

TEST_PAYLOAD = ts4.Cell('te6ccgEBAQEAMAAAW1t00puAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACLA=')
TEST_PAYLOAD_2 = ts4.Cell('te6ccgEBAQEAMAAAW1t00puAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHJA=')

EXPECTED_WALLET_OWNER_BALANCE = ts4.globals.G_DEFAULT_BALANCE - DEPLOY_WALLET_VALUE
